name: Release

on:
  push:
    branches: [ main ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: zip -r ITEM.zip . -x ".github/*" ".git/*" "*.docker/*" ".gitignore"

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          configuration: ".github/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: ITEM.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}